pipeline:
  name: docker-ecr-pipeline1
  identifier: dockerecrpipeline1
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1779478413335
        repoName: anupam-bkp/hello-world-docker.git
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - step:
                  type: Action
                  name: setup-jdk-21
                  identifier: Setup_JDK_21
                  spec:
                    uses: actions/setup-java@v3
                    with:
                      distribution: temurin
                      java-version: "21"
              - step:
                  type: Run
                  name: build_java_jar
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      # Verify Java and Maven installation
                      java -version
                      mvn -version
                      mvn clean package -Dmaven.compiler.source=21 -Dmaven.compiler.target=21 -Dmaven.compiler.release=21
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: awsecrconnector1
                    region: ap-south-2
                    account: "500766168750"
                    imageName: learner/hello-world-docker
                    tags:
                      - latest
